/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-01 14:54:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TrafficLive_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1578469475550L));
    _jspx_dependants.put("jar:file:/D:/javaproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write(" <meta name=\"viewport\" content=\"initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<meta name=\"robots\" content=\"index, follow\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/top.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ltbox.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/circleReset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/circleStyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/trafficeLive.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/echarts.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-2.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/common.js\"></script>\r\n");
      out.write("<script src=\"js/date.js\"></script>\r\n");
      out.write("<script src=\"js/source/online.js\"></script>\r\n");
      out.write("<script src=\"js/html5_3d_animation.js\"></script>\r\n");
      out.write("<script>\t\r\n");
      out.write("   \t\tdocument.addEventListener('plusready', function(){\r\n");
      out.write("   \t\t\t//console.log(\"所有plus api都应该在此事件发生后调用，否则会出现plus is undefined。\"  \t\t\t\r\n");
      out.write("   \t\t}); \r\n");
      out.write("   \t\t$(function() {\r\n");
      out.write("   \t\t\tvar window_width=$(window).width();\r\n");
      out.write("   \t\t\tvar window_height=$(window).height()\r\n");
      out.write("\t\t    $(\"#html5_3d_animation\").html5_3d_animation({\r\n");
      out.write("\t\t        window_width:window_width,\r\n");
      out.write("\t\t        window_height:window_height+200,\r\n");
      out.write("\t\t        window_background: '#00040d',\r\n");
      out.write("\t\t        star_count: '250',\r\n");
      out.write("\t\t        star_color: 'rgba(100,149,237,0.9)',\r\n");
      out.write("\t\t        star_depth: '400'\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    $(window).resize(function(){\r\n");
      out.write("\t\t    \tvar window_width=$(window).width();\r\n");
      out.write("\t   \t\t\tvar window_height=$(window).height()\r\n");
      out.write("\t\t\t    $(\"#html5_3d_animation\").html5_3d_animation({\r\n");
      out.write("\t\t\t        window_width:window_width,\r\n");
      out.write("\t\t\t        window_height:window_height+200,\r\n");
      out.write("\t\t\t        window_background: '#02050a',\r\n");
      out.write("\t\t\t        star_count: '250',\r\n");
      out.write("\t\t        \tstar_color: 'rgba(100,149,237,0.9)',\r\n");
      out.write("\t\t        \tstar_depth: '400'\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}); \t\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"js/circle.js\" ></script>\r\n");
      out.write("<style>\r\n");
      out.write("    \t@media screen and (max-width: 2000px) {\r\n");
      out.write("    \t\t#mapContainer {\r\n");
      out.write("    \t\t\theight: 850px;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \t@media screen and (max-width: 1400px) {\r\n");
      out.write("    \t\t#mapContainer {\r\n");
      out.write("    \t\t\theight: 500px;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t#submit_btn1{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/1.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("  #submit_btn2{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/2.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("  #submit_btn3{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/3.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("  #submit_btn4{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/4.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("   #submit_btn5{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/5.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("   #submit_btn6{\r\n");
      out.write("           width:400px;   \r\n");
      out.write("           height:200px;   \r\n");
      out.write("           background:url(img/6.png) no-repeat center;   \r\n");
      out.write("           cursor:pointer;   \r\n");
      out.write("  /* 上面的代码是常规设置， 即：引入一个图片背景，设置在中心位置，大小和按钮的大小一致，以及鼠标指针为手型 */  \r\n");
      out.write("    \r\n");
      out.write("            display:block;   \r\n");
      out.write("            font-size:0;   \r\n");
      out.write("            line-height:0;   \r\n");
      out.write("            text-indent:-9999px;\r\n");
      out.write("            margin-top:50px;\r\n");
      out.write("            margin-left:50px;\r\n");
      out.write("  /* 上面的不用多问，四句一起拷贝就可以了，大概意思就是把value值设置为0像素，也就是肉眼无法看到，但却又是存在的（用$_POST['submit_btn'] 可以证明）*/  \r\n");
      out.write("  }  \r\n");
      out.write("  #left_one{\r\n");
      out.write("  width:500px; \r\n");
      out.write("  height:250px;\r\n");
      out.write("  float: left;\r\n");
      out.write("  margin-top:50px\r\n");
      out.write("  }  \r\n");
      out.write("    #right_one{\r\n");
      out.write("  width:500px; \r\n");
      out.write("  height:250px;\r\n");
      out.write("  float: right;\r\n");
      out.write("  margin-top:50px\r\n");
      out.write("  }  \r\n");
      out.write("    </style>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main bg\">\r\n");
      out.write("\t\t<canvas id=\"html5_3d_animation\"></canvas>\r\n");
      out.write("\t\t<!-- 这是圆圈导航 -->\r\n");
      out.write("\t\t<div class=\"radmenu\">\r\n");
      out.write("\t\t\t  <a href=\"#\" class=\"show\" draggable='false'>数据展示</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t      <a href=\"index.jsp\">首页</a>\r\n");
      out.write("\t\t\t    </li>\r\n");
      out.write("\t\t\t    <li>\r\n");
      out.write("\t\t\t      <a href=\"TrafficImpression.jsp\">关于我们</a>\r\n");
      out.write("\t\t\t    </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class='contentWrap'>\r\n");
      out.write("\t\t\t<!-- 导航栏 -->\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<!--logo-->\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t新加坡爱彼迎数据分析<small></small>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--导航-->\r\n");
      out.write("\t\t\t\t<div class=\"nav_menu nav\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.jsp\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"on\">数据展示</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"TrafficImpression.jsp\">关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--时间，设置，帮助-->\r\n");
      out.write("\t\t\t\t<div class=\"nav_extra\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"date\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--星期-年/月/日-->\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"date1\"></p> <!--时-分-秒-->\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"date2\"></p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 平台主题 -->\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("<!-- 图1 -->\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">新加坡爱彼迎好评前十的酒店的数据分析</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"test1\" method=\"post\">\r\n");
      out.write("\t                <input type=\"submit\" value=\"进入数据展示\" id=\"submit_btn1\"/>\r\n");
      out.write("                                        </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- 图2 -->\t\t\t\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">新加坡爱彼迎回头率前十的酒店的数据分析</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"test2\" method=\"post\">\r\n");
      out.write("\t                <input type=\"submit\" value=\"进入数据展示\" id=\"submit_btn2\"/>\r\n");
      out.write("                                        </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- 图3 -->\t\t\t\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">新加坡各地区酒店数量分析</div>\r\n");
      out.write("\t\t\t\t\t<a id=\"submit_btn3\" href=\"test3.jsp\"></a>\r\n");
      out.write("\t\t<!--  <object type='text/html' data='test3.jsp' id='submit_btn3'></object>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- 图4 -->\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">新加坡地区各酒店位置分析</div>\r\n");
      out.write("\t\t\t\t\t<a id=\"submit_btn4\" href=\"test4.jsp\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- 图5 -->\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">新加坡中心地区酒店价格分析</div>\r\n");
      out.write("\t\t\t\t\t<a id=\"submit_btn5\" href=\"test5.jsp\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!-- 图6 -->\r\n");
      out.write("\t\t\t<div id=\"left_one\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_title\">京珠高速 : 人群职业分布图表</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"test6\" method=\"post\">\r\n");
      out.write("\t                <input type=\"submit\" value=\"进入数据展示\" id=\"submit_btn6\"/>\r\n");
      out.write("                                        </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 导航栏实时显示时间 -->\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("$(function a(){\r\n");
      out.write("\t$(\"#ch2_1\").hide();\r\n");
      out.write("\t$(\"#ch2_2\").hide();\r\n");
      out.write("\t$(\"#ch3_1\").hide();\r\n");
      out.write("\t$(\"#ch3_2\").hide();\r\n");
      out.write("\t$(\"#ch1_1\").show();\r\n");
      out.write("\t$(\"#ch1_2\").show();\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var date1 = document.getElementById(\"date1\");\r\n");
      out.write("\t\tvar date2 = document.getElementById(\"date2\");\r\n");
      out.write("\t\tvar haha = new Date();\r\n");
      out.write("\t\tdate1.innerHTML = haha.getWeek() + \"   \" + haha.format(\"YY-MM-DD\");\r\n");
      out.write("\t\tdate2.innerHTML = haha.getNowTime();\r\n");
      out.write("\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\tdate1.innerHTML = haha.update(\"week\") + \"   \" + haha.update(\"YYYY-MM-DD\");\r\n");
      out.write("\t\t\tdate2.innerHTML = haha.update(\"nowTime\");\r\n");
      out.write("\t\t\tsetTimeout(arguments.callee,50)\r\n");
      out.write("\t\t},50)\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#load1\").click(function(){\r\n");
      out.write("\t$(\"#ch1_1\").show(1000);\r\n");
      out.write("\t$(\"#ch1_2\").show(1000);\r\n");
      out.write("\t$(\"#ch2_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch2_2\").hide(1000);\r\n");
      out.write("\t$(\"#ch3_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch3_2\").hide(1000);\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#load2\").click(function(){\r\n");
      out.write("\t$(\"#ch2_1\").show(1000);\r\n");
      out.write("\t$(\"#ch2_2\").show(1000);\r\n");
      out.write("\t$(\"#ch1_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch1_2\").hide(1000);\r\n");
      out.write("\t$(\"#ch3_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch3_2\").hide(1000);\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#load3\").click(function(){\r\n");
      out.write("\t$(\"#ch3_1\").show(1000);\r\n");
      out.write("\t$(\"#ch3_2\").show(1000);\r\n");
      out.write("\t$(\"#ch1_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch1_2\").hide(1000);\r\n");
      out.write("\t$(\"#ch2_1\").hide(1000);\r\n");
      out.write("\t$(\"#ch2_2\").hide(1000);\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(document).on(\"click\",'button',function(){\r\n");
      out.write("\t  $(\"button\").each(function(n,value){\r\n");
      out.write("\t\t  $(value).removeClass(\"trafbtn selected\");\r\n");
      out.write("\t  })\r\n");
      out.write("\t  $(this).addClass(\"trafbtn selected\")\r\n");
      out.write("  })\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
